/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    IEpTopRight: typeof import('~icons/ep/top-right')['default']
    MovieCard: typeof import('./src/components/common/MovieCard.vue')['default']
    MoviesContainer: typeof import('./src/components/common/MoviesContainer.vue')['default']
    NavMenu: typeof import('./src/components/common/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
